import {StyleSheet,Dimensions} from 'react-native'
const {width:innerWidth} = Dimensions.get('window');
const {height:innerHeight}=Dimensions.get('window');
export const styles = StyleSheet.create({
    menuContainer:{
        width:"100%",
        flexDirection:"row",
        height:50,
    },
    searchContainer:{
        width:"71%",
        backgroundColor:"#FFFFFF",
        flexDirection:"row",
        display:"flex",
        paddingLeft:10,
        alignItems:'center',
        zIndex:2
    },
    iconBack:{
        flex:1,
        width:20,
        height:20,
        resizeMode:'contain',
        marginRight:15
    },
    cartIconContainer:{
        width:"10%",
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:"#FFFFFF",
       zIndex:1
    },
    cartIcon:{
        width:40,
        height:40,
    },
    searchIconContainer:{
        width:"10%",
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:"#FFFFFF",
    },
    buttonProfileContainer:{
        width:"10%",
        height:"100%",
        borderRadius:6,
        backgroundColor:"#FFFFFF",
    },
    buttonProfile:{
        height:100
    },
    point:{
        width:6,
        height:6,
        borderRadius:8,
        backgroundColor:"#757575",
    },
    threePoint:{
        paddingTop:13,
        flexDirection:"column",
        justifyContent:"space-around",
        alignItems:"center",
        height:"100%",
        backgroundColor:"#FFFFFF",
        paddingBottom:10
    },
    searchIcon:{
        width:20,
        height:20,
       
    },
    textInput:{
        flex:8
    },
    wrapper:{
        position:'absolute',
        backgroundColor:'rgba(0,0,0,0.7)',
        width:innerWidth,
        height:innerHeight,
        zIndex:3

    },
    menu:{
        width:innerWidth*0.8,
        height:innerHeight,
        position:'absolute',
        zIndex:4,
        
    },
    header:{
        height:"23%",
        display:'flex',
        backgroundColor:'#06D6A0',
    },
    body:{
        
        height:"77%",
        display:'flex',
        backgroundColor:'white'
    },
    avatar:{
        width:70,
        height:70,
        borderRadius:35,
        marginTop:10,
        marginLeft:10,
    },
    textPrimary:{
        fontWeight:'bold',
        color:'white',
        marginTop:15,
        marginLeft:20,
       
    },
    text:{
        color:"white",
        marginLeft:7,
        fontSize:12,
        paddingTop:5,
        fontWeight:'500',
      
    },
    menuItem:{
        padding:10,
       fontWeight:'bold',
       shadowOffset:{width:1,height:1},
       elevation:0.5,
       borderBottomWidth:0.1,
       
    }
}); 